name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16 # current lts
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build code
        run: yarn lint
